### ISSUE TITLE
Feature request: Loggerを提供してほしい

### ISSUE THREAD

**Issue by r3-yamauchi** [kintone/js-sdk-ja#10]
https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/src/client/RecordClient.ts#L88
で console.warn が使われていますが、console出力するかどうかを 出力レベルを指定して制御できるようにならないでしょうか。

また、 @kintone/rest-api-client が
https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Logger/ConsoleLogger.ts
のような Logger を提供してくれたら初心者にも優しいと思います。

**Comment by chick-p** [comment]
https://github.com/kintone/js-sdk-ja/issues/10#issuecomment-596342116 のコメントの通り、wontfix としてクローズします。
