### ISSUE TITLE
Feature request: 'User-Agent' request header

### ISSUE THREAD

**Issue by r3-yamauchi** [kintone/js-sdk-ja#11]
セキュアコーディング ガイドライン
https://developer.cybozu.io/hc/ja/articles/201919400
で

> 適切なユーザーエージェントを設定する
> どのようなサービスやツールからリクエストを送信しているか判別可能にするために、適切なユーザーエージェント(User-Agent ヘッダー)を設定してください。

が求められており、またサイボウズ側でログの解析や集計を行うために User-Agent ヘッダーを設定するように依頼されています。

KintoneRestAPIClient のインスタンスを作る際に User-Agent ヘッダーに設定される識別子を指定（必須？）できるようにしていただきたいです。

**Comment by chick-p** [comment]
@r3-yamauchi 
@kintone/rest-api-client v1.13.0 で、Node.js 環境の場合に 任意の User-Agent 文字列を渡せるようになりました。
`KintoneRestAPIClient` を生成するときのオプションで指定できます。

ブラウザ環境についても今後検討いたしますが、この Issue は一旦 Close させていただきます。
よろしくお願いいたします。
