### ISSUE TITLE
puppeteerの起動オプションを追加指定出来るようにしてほしい

### ISSUE THREAD

**Issue by rktyt** [kintone/js-sdk-ja#15]
## Package（対象パッケージ）

- @kintone/plugin-uploader

## Why（なぜ）

Dockerコンテナー内(debian 10)で機能しないため。

エラー内容
> Error: Failed to launch the browser process!
[0210/200834.467008:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

## What（何を）

```javascript
puppeteer.launch([
  '--no-sandbox',
  '--disable-setuid-sandbox'
])
```

こうしたいのですが、現状外部から（コマンドライン含む）指定出来ません。

**Comment by shisama** [comment]
@rktyt ありがとうございます。Puppeteer へのオプションの渡し方も含めて検討します。

**Comment by mshrtsr** [comment]
@rktyt 
こちら、対応が遅くなり申し訳ありません。
Dockerコンテナ内でplugin-uploaderを利用する方法ですが、
以下のトラブルシューティングを試していただけますでしょうか？

> Running Puppeteer in Docker

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker

実際に上記の方法でデモプロジェクトを作成してみたところ、
一般ユーザの追加を行うことでDockerコンテナ内でplugin-uploaderを利用することができました。
https://github.com/tasshi-playground/demo-kintone-plugin-uploader-in-docker

※公式のドキュメントによると`--no-sandbox`を使うのは強く非推奨とのことです。
> NOTE: Running without a sandbox is strongly discouraged. Consider configuring a sandbox instead.

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox

---
`--no-sandbox`以外にもplugin-uploader内部のPuppeteerに対してオプションを渡したいケースはあると考えられるので、検討は引き続き進めていきたいと思います！

**Comment by mshrtsr** [comment]
@rktyt 
こちらクローズとさせていただきます。
また問題発生しましたら改めてIssueの登録をお願いします。
