### ISSUE TITLE
`baseUrl`に誤って`http`と書いてしまった場合のエラーが分かりづらい

### ISSUE THREAD

**Issue by the-red** [kintone/js-sdk-ja#17]
## Target Package（対象パッケージ）

- @kintone/rest-api-client 1.0.0 ～ 1.11.2

## Environment（環境）

- Operating System（OS）: Windows10 WSL2
- Node.js version（Node.js環境の場合）: 14.15.3

## Current Behavior（現在の挙動）

`baseUrl`に誤って`http`と書いてしまった場合に、
関数によってはしれっと動いてしまうものもあれば、エラーが出るものもあって動作が不定です。
エラーが出る関数も、メッセージが変な感じです。

確認できた範囲では

* getRecord: 何故か動く
* updateRecord: 何故か動く
* addRecord: エラーになるが、メッセージが変

addRecordとしては正しいパラメータを渡しているのに、
あたかもパラメータが不足してるような、こんなエラーが出ます。
（そもそもaddの場合はidの指定は不要）
```
{ app: { messages: [ '必須です。' ] }, id: { messages: [ '必須です。' ] } }
```

サンプルコードこんな感じです。
インラインで挙動をコメント入れてます。

```js
const { KintoneRestAPIClient } = require('@kintone/rest-api-client');
const client = new KintoneRestAPIClient({
  baseUrl: 'http://example.cybozu.com', // TYPO: not "https" but "http"
  auth: { type: 'apiToken', apiToken: 'xxxxxxxxxxxxxxxxxxxxxx' },
});

// Request succeeded for some reason.
client.record
  .getRecord({ app: 115, id: 1 })
  .then(console.log) // { record: { レコード番号: {...}, メモ: {...}, ... } }
  .catch(console.error);

// Request succeeded for some reason.
client.record
  .updateRecord({ app: 115, id: 1, record: { メモ: { value: 'foobarbaz' } } })
  .then(console.log) // { revision: '3' }
  .catch(console.error);

// Request failed, but the error message is wrong.
client.record
  .addRecord({ app: 115, record: { メモ: { value: 'foobarbaz' } } })
  .then(console.log)
  .catch((_) => console.error(_.errors)); // Error { app: { messages: [ '必須です。' ] }, id: { messages: [ '必須です。' ] } }
```

## Expected Behavior（期待する挙動）

そもそも`http`でのリクエストはできないので、
`baseUrl`に`http`と書いてコンストラクタを呼んでしまった時点で
問答無用でエラーにしてもらいたいです。

`https`と書けば全く問題なく動くのですが、
エラーメッセージが変なので、typoしたあとの原因究明に時間がかかりました。

**Comment by zaki-yama** [comment]
@the-red 
ご報告ありがとうございます。
protocolとしてhttpも許容しているのは `http://localhost:8888` のような開発用モックサーバーでの利用も想定していたからでした。
しかしながら、記載いただいたケースでエラー内容がわかりづらくデバッグに苦労する、というご意見は非常に理解します。

発生している挙動の原因を引き続き調査しつつ、baseUrlとして受け付ける文字列のバリデーションを厳しくするなど、対応を検討いたします。

**Comment by mshrtsr** [comment]
@the-red 
こちら、localhost以外ではhttpsを強制する方針で修正いたしました！
次回のリリースで反映予定です。

**Comment by the-red** [comment]
@mshrtsr ありがとうございました！！
