### ISSUE TITLE
アプリアクションに対応してほしい

### ISSUE THREAD

**Issue by akira345** [kintone/js-sdk-ja#18]
## Package（対象パッケージ）

- @kintone/rest-api-client

## Why（なぜ）

公式APIでアプリアクションの設定取得、更新が[サポートされました。](https://kintone.cybozu.co.jp/update/all/210314.html)

それに伴い、rest-api-clientでもアプリアクションのサポートをしてほしい。

## What（何を）

kintoneアプリに対し、アプリアクションの設定取得、更新を行うことができる。

**Comment by shintaroNagata** [comment]
@akira345 
要望ありがとうございます！
近日中に rest-api-client でも対応することを計画しています。

**Comment by shintaroNagata** [comment]
@akira345 
こちら、https://github.com/kintone/js-sdk/pull/833 で対応した後、rest-api-client の v1.13.0 でリリースしました。ご確認ください。
こちらの issue としては close させていただきます。ありがとうございました！
