### ISSUE TITLE
dts-genで生成した型をrest-api-client のジェネリクス型引数に渡すとエラーになる

### ISSUE THREAD

**Issue by the-red** [kintone/js-sdk-ja#19]
## Target Package（対象パッケージ）

- @kintone/dts-gen 3.1.12
- @kintone/rest-api-client 1.13.0

## Environment（環境）

- Operating System（OS）: Windows 10
- Browser（ブラウザ環境の場合）: Google Chrome
- Node.js version（Node.js環境の場合）: 12.10.0
- TypeScript version: 4.2.4

## Current Behavior（現在の挙動）

rest-api-clientで`client.record.getAllRecords<T>()` を呼ぶときに、
dts-genで生成された`SavedXxxFields`を`T`にそのまま渡すと、
こんなエラーが出てしまいます。

```js
client.record.getAllRecords<kintone.types.SavedXxxFields>(params)
```
```
型 'SavedXxxFields' は制約 'Record' を満たしていません。
型 'SavedXxxFields' のインデックス シグネチャがありません。
```

調べたところ、フィールドのプロパティ`type` `value`のうち、
`type`がdts-genではオプションなのに対し、
https://github.com/kintone/js-sdk/blob/e054f514677c3e712b34c56e09fda749065804c9/packages/dts-gen/kintone.d.ts#L260-L265

rest-api-clientでは必須のため、エラーになっているようでした。
https://github.com/kintone/js-sdk/blob/974bb73aca45f52bf30f2ce611e34f90482d7b74/packages/rest-api-client/src/KintoneFields/types/field.ts#L1-L4

型ライブラリts-essentialsのDeepRequiredを使って、
https://github.com/krzkaczor/ts-essentials

こうラップしてやると、エラーは回避できました。
```js
client.record.getAllRecords<DeepRequired<kintone.types.SavedXxxFields>>(params)
```

## Expected Behavior（期待する挙動）

dts-genが生成する型をそのままrest-api-clientに渡して
エラーなく通るようにしていただきたいです。

```js
client.record.getAllRecords<kintone.types.SavedXxxFields>(params)
```

`SavedXxxFields`以外の新しい型定義が別途生成されても構いません。
自分でラップするのは流石につらいもので・・・

**Comment by zaki-yama** [comment]
@the-red 
ご報告ありがとうございます。
本件は検討すべき事項として認識しており、js-sdk側で https://github.com/kintone/js-sdk/issues/445 を登録済みです。
そちらの issue にも記載がありますが、実現方法の検討や型定義周りの整理を今後進めていきます。

**Comment by the-red** [comment]
本家ですでにプルリク出ていたのですね。失礼しました。改善お待ちしてます！

紛らわしいので、こっちはクローズしてもらって大丈夫です。

**Comment by zaki-yama** [comment]
ありがとうございます。それではこちらはクローズさせていただきます。
