### ISSUE TITLE
upsertAllRecordsはいつ頃リリースされるでしょうか？

### ISSUE THREAD

**Issue by the-red** [kintone/js-sdk-ja#20]
## Package（対象パッケージ）

- @kintone/rest-api-client

## Why（なぜ）

https://github.com/kintone/js-sdk/tree/upsert-all-records/packages/rest-api-client
こんなブランチを見つけました。
upsertRecordを大変便利に使っているので、
upsertAllRecordsもあるとさらに便利なのですが、いつ頃リリースされるでしょうか？

https://github.com/kintone/js-sdk/commit/41a46fb0b7f20bbca883bf9e0d5cb99f594371e0#diff-b46af22d2b235a8108f83902a79e93fcbc8b0e94d0e96a95aeca444276152a28
昨年5月にこんなコミットで実装もされてるようなので、
実はずっとリリースを待っていました。
最新のv2.0にもまだ入ってないようなのですが、
リリース出来ない理由が何かあったりするのでしょうか？

**Comment by shintaroNagata** [comment]
@the-red 
フィードバックありがとうございます！

`upsertAllRecords` に関しては、現在リリースの予定はありません。
また、そちらのコミットはあくまでもプロトタイプとして実装したものになります。

実際に rest-api-client の機能として提供するには、そもそもの提供の是非やパラメータ／レスポンスの形式、エラー時の挙動等を検討するための判断材料が不足している状態です。 

差し支えなければ、そちらの機能を利用したいと思った背景や実際のユースケースについて、教えていただくことは可能でしょうか？

**Comment by the-red** [comment]
@shintaroNagata 
js-sdk時代には、1500件の制限はありますがupsertRecordsで複数登録できていて、
これを今でもプロダクション環境で使っています。
rest-api-clientにこれが実装されないと、完全移行がいつまでもできません。
https://kintone-labs.github.io/kintone-js-sdk/latest/reference/record/#upsertrecordsparams

用途は色々ありますが、たとえば売り上げを集計する以下のような要件の場合、
upsertが複数レコード同時にできると大変便利です。

* 事業所別売上アプリ：事業所単位の月間売上が登録されている
* 売上集計アプリ：全事業所を合算した月間売上が登録されている
* ボタンクリックで事業所別アプリ→売上集計アプリに当月の売り上げをマージ
  * 月の途中で現状確認のためにマージして、何度も繰り返すことがある

レコード数の上限はあってもよいので、
「複数レコードのupsert」の実装をぜひお願いします。

ちなみに、旧js-sdkにあったメソッドは、
原則全部rest-api-clientに移してもらえると思っていたのですが、
そうでもないのでしょうか？

**Comment by shintaroNagata** [comment]
背景についての詳細情報、ありがとうございます！今後の機能追加検討の際の参考にさせていただきます。

> ちなみに、旧js-sdkにあったメソッドは、
原則全部rest-api-clientに移してもらえると思っていたのですが、
そうでもないのでしょうか？

rest-api-client はkintone-js-sdk などの類似のクライアントを参考にしつつも、新しいライブラリとして開発が行われているので、提供する機能に関しては開発時に個別に判断を行なっています。
現状では、直近での`upsertRecords`相当の機能の提供は予定していませんが、今後要望が多ければ優先的に検討していこうと思います。

**Comment by shintaroNagata** [comment]
@the-red 
背景についての詳細情報、ありがとうございます！今後の機能追加検討の際の参考にさせていただきます。

> ちなみに、旧js-sdkにあったメソッドは、
原則全部rest-api-clientに移してもらえると思っていたのですが、
そうでもないのでしょうか？

rest-api-client はkintone-js-sdk などの類似のクライアントを参考にしつつも、新しいライブラリとして開発が行われているので、提供する機能に関しては開発時に個別に判断を行なっています。
現状では、直近での`upsertRecords`相当の機能の提供は予定していませんが、今後要望が多ければ優先的に検討していこうと思います。

**Comment by Lorenzras** [comment]
I badly need this feature. I have an internal request to sync data from multiple platforms into our kintone database.
For now, I am using puppeteer when inserting large amounts of data without costing me API calls.

私もこの機能がほしいです。複数のサービスからKintoneのデータベースに同期する社内の案件があります。
とりあえず、API呼び出し回数がかからない、puppeteerを利用しています。
