### ISSUE TITLE
エラーメッセージの多言語対応

### ISSUE THREAD

**Issue by potaracom** [kintone/js-sdk-ja#21]
## Package（対象パッケージ）

- @kintone/rest-api-client

## Why（なぜ）

エラーメッセージをユーザー画面に表示します。
エラーメッセージを多言語対応するか、エラーコードとエラーメッセージの一覧を公開して欲しいです。

## What（何を）

利用者に適切なエラー対応を案内したい。

**Comment by potaracom** [comment]
APIトークン利用時のみ言語が問題になることがわかりました。
エラー一覧を公開してほしいという気持ちはありますが、この場所での提案は適切ではないのでクローズします 😸

**Comment by zaki-yama** [comment]
こちらクローズしていただいてますが、リクエストありがとうございました！

**Comment by zaki-yama** [comment]
@potaracom 
こちら、すでにクローズしていただきましたが、登録ありがとうございました！
