### ISSUE TITLE
@cybozu/eslint-configと@kintone/dts-genの併用に際する型の統一の要望

### ISSUE THREAD

**Issue by kk3939** [kintone/js-sdk-ja#22]
## Package（対象パッケージ）

- @kintone/dts-gen

## Why（なぜ）

- @cybozu/eslint-config のtypescript のpresetと＠kintone/dts-genを併用する際に、生成されるファイルが@cybozu/eslint-configのルールに統一されることで修正する手間が省け、スムーズに開発したいため。

## What（何を）

@cybozu/eslint-config のtypescript のpresetと＠kintone/dts-genを併用しています。
コマンドを打ち、table フィールドの型を含むd.tsファイルを生成すると下記の画像のように、eslintのエラーが出ます。

![スクリーンショット 2021-10-29 17 38 14](https://user-images.githubusercontent.com/45879786/139405301-8b88799c-a2eb-4682-b352-44884d05a3c0.png)

![スクリーンショット 2021-10-29 17 38 33](https://user-images.githubusercontent.com/45879786/139405588-80f2acef-0d32-47f4-85e6-947f81fb043c.png)

これを@cybozu/eslint-config（typescript-eslint）の書き方に統一してほしいです。

![スクリーンショット 2021-10-29 17 51 57](https://user-images.githubusercontent.com/45879786/139406136-eedf0696-d8be-4d58-b775-79cebdc323d0.png)

**Comment by shintaroNagata** [comment]
@kk3939 
フィードバックありがとうございます！
対応検討します。

**Comment by mshrtsr** [comment]
@kk3939 
こちら、https://github.com/kintone/js-sdk/pull/1266 にて対応いたしました。
先ほどリリースされた `@kintone/dts-gen 6.1.0` 以降で反映済みです。
