### ISSUE TITLE
create pluginでuploderをインストールした際にuploadできない

### ISSUE THREAD

**Issue by kk3939** [kintone/js-sdk-ja#23]
## Target Package（対象パッケージ）
- create-plugin
- plugin-uploader

- @kintone/create-plugin

## Environment（環境）

- Operating System（OS）: mac OS
- Node.js version（Node.js環境の場合）: 16.3.0

## Current Behavior（現在の挙動）

`npx create-kintone-plugin {plugin_name}`のコマンドを打った際に、plugin-uploaderをインストールするようにセットアップしました。

>  ? @kintone/plugin-uploaderを使いますか？ Yes

そのまま`npm start`コマンドを打つとuploadできるはずが、表示が下記のまま進まず、uploadできません。

```
Try to upload plugin.zip
```

## Expected Behavior（期待する挙動）

create-pluginからplugin-uploaderをinstallした際も通常通り動作して欲しいです。

おそらく下記リンクと同じ現象が起きていると思います。
https://developer.cybozu.io/hc/ja/articles/360000877946/comments/4402479227673

createコマンドで作成した際に自動でインストールされるversionが` "@kintone/plugin-uploader": "^4.3.0",`でした。

確認していただけると幸いです。

**Comment by mshrtsr** [comment]
@kk3939 
フィードバックありがとうございます。
報告していただいた挙動はおそらく kintone/js-sdk#886 の不具合だと考えられます。こちらの不具合は最新バージョンでは修正済みです。
npxで実行されているのですが、古いバージョンのcreate-pluginがグローバルインストールされている可能性があります。
一度以下のアップグレードコマンドを実行後に再度お試しいただけますでしょうか？
`npm update -g @kintone/create-plugin`

※記載していただいた`npx create-kintone-plugin {plugin_name}`コマンドではPCにインストールされたcreate-pluginを実行しています。最新バージョンをダウンロードして実行するには`npx @kintone/create-plugin {plugin_name}`コマンドの実行をお願いします。

**Comment by kk3939** [comment]
@mshrtsr 迅速な返信ありがとうございます。🙇‍♂️

指摘していただいた通りで、
`npm ls -g`で確認したところバージョンが古かったためアップデートしたら解消しました。

また、npxの使用方法も丁寧に答えていただき助かりました。🙏

**Comment by mshrtsr** [comment]
@kk3939 
ありがとうございます、動作したようで良かったです。
こちらクローズさせていただきます。
