### ISSUE TITLE
Axiosの問題（仕様？）でプロキシ経由でのアクセスができない

### ISSUE THREAD

**Issue by the-red** [kintone/js-sdk-ja#24]
## Target Package（対象パッケージ）

- @kintone/rest-api-client 2.0.28
## Environment（環境）

- Operating System（OS）: macOS 12.0.1
- Browser（ブラウザ環境の場合）:
- Node.js version（Node.js環境の場合）: v16.13.0

## Current Behavior（現在の挙動）

ブラウザではなく、Node.jsから使ったときの挙動です。

Axiosの標準機能のproxyでは、弊社で使っているプロキシサーバー経由ではうまくつながらず、
このIssueに載っているように、
https-proxy-agent、node-tunnelのどちらかを併用する必要があります。
https://github.com/axios/axios/issues/2072#issuecomment-609650888

旧js-sdk時代にhttpsプロキシ機能をお願いしたことがあり、
このときはnode-tunnelを使って実装してもらっていたので、
弊社プロキシでもちゃんと動いていました。
https://github.com/kintone-labs/kintone-js-sdk/pull/34

rest-api-clientになって、動かないなーと思っていて、
原因もわかっていたのですが、Issueを上げるのが遅くなりました。

## Expected Behavior（期待する挙動）

プロキシの処理をhttps-proxy-agent、node-tunnelのどちらかにして、
安定してプロキシ経由のアクセスが出来るようにしてほしい。

自分でも色々と試しているのですが、
https-proxy-agentを使う場合は
クライアント証明書もhttps.Agentなので、
同時に使う方法がよくわかりませんでした。

一方node-tunnelは、httpとhttpsの組み合わせで4種類のメソッドに分かれるので、
呼び出し方も4通りに分かれてしまいそうで面倒ですね。。

なにか良い解決法があればよいのですが。

**Comment by the-red** [comment]
たとえば、コンストラクタに自作の`https.Agent`を渡せるようにしてもらえると、
必要に応じて柔軟に使うことができる気がしました。
こんなのいかがですかねぇ？？

```js
const client = new KintoneRestAPIClient({
  baseUrl: "https://example.cybozu.com",
  auth: {
    username: process.env.KINTONE_USERNAME,
    password: process.env.KINTONE_PASSWORD,
  },
  agent: new HttpsProxyAgent("https://proxy.example.com:443"),
});
```

agentが指定されたら、
SDK内でagentを生成する処理（クライアント証明書のオプションなど）は無視されるイメージです。

**Comment by mshrtsr** [comment]
@the-red 
フィードバックありがとうございます！

報告していただいた挙動ですが、ご指摘の通りAxiosの仕様によるものですね。

## Axiosの挙動
1. クライアントは HTTP リクエストラインの URI を絶対パスに書き換えてプロキシサーバにリクエストを送信する
2. プロキシサーバはリクエストを暗号化し宛先サーバに送信する

該当コード: https://github.com/axios/axios/blob/e426910be7c417bdbcde9c18cb184ead826fc0e1/lib/adapters/http.js#L174

![axios-with-proxy](https://user-images.githubusercontent.com/33759872/146502790-73785818-2ec6-45ef-b0e1-75a48bb2532f.png)

こちらの挙動はRFCで定義されているのですが、サーバ側の対応は任意であるため正常に処理できない場合があります。  
https://datatracker.ietf.org/doc/html/rfc7230#section-5.3.2

## https-proxy-agentを利用した場合の挙動
一方で、提案していただいた[https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent)を利用した場合は以下の挙動になります。

1. クライアントはプロキシサーバに CONNECT リクエストを送信する
2. プロキシサーバは宛先サーバに TCP コネクションを繋ぐ
3. クライアントはプロキシサーバ経由で暗号化されたリクエストを宛先サーバに送信する

![curl-with-proxy](https://user-images.githubusercontent.com/33759872/146502809-56049934-fc41-46dc-89e6-3bc6914ade24.png)

こちらもRFCで定義されています。  
https://datatracker.ietf.org/doc/html/rfc2817#section-5.3

しかし、ブラウザではセキュリティ上の問題から`CONNECT`メソッドを使用することができません。

- XMLHttpRequest (XHR)
  - https://xhr.spec.whatwg.org/#the-open()-method
  - > Throws a "SecurityError" DOMException if method is a case-insensitive match for CONNECT, TRACE, or TRACK.
- Fetch API
  - https://fetch.spec.whatwg.org/#methods
  - > A forbidden method is a method that is a byte-case-insensitive match for CONNECT, TRACE, or TRACK.

参考記事: [VU#150227 - HTTP proxy default configurations allow arbitrary TCP connections](https://www.kb.cert.org/vuls/id/150227)

## 対応方針について

@kintone/rest-api-client は現在 Node.js／ブラウザの両環境で利用いただけるクライアントライブラリとして提供しています。
そのため動作や仕様設計を上記のような環境による差異を考慮したものにする必要あるので、追加のコメントで提案していただいた案も含めて改めて検討させていただこうと思います！

**Comment by the-red** [comment]
@mshrtsr 
すごい！図まで描いていただいてありがとうございます！！！

> @kintone/rest-api-client は現在 Node.js／ブラウザの両環境で利用いただけるクライアントライブラリとして提供しています。
そのため動作や仕様設計を上記のような環境による差異を考慮したものにする必要あるので、追加のコメントで提案していただいた案も含めて改めて検討させていただこうと思います！

調査中にサイボウズさんのこのブログも読みました。
https://blog.cybozu.io/entry/2020/10/23/170000

> HTTP Client 自体のインターフェイスだけでなくレスポンスについても http のレイヤーにインターフェイスとして定義しているため、axios から別の HTTP Client に変えたい場合にも http のレイヤーの中で対応できます。 現状は axios を使うことで Node.js 環境での Proxy やクライアント証明書対応が簡単に行えるようになっていますが、将来的にブラウザ環境と Node.js 環境それぞれで異なる HTTP Client を使いたいという場合にも対応可能な設計になってます。

これってまさに、今回のような問題があったときに、
ブラウザとNode.jsで別の処理にしちゃうことも可能ということですよね？？

ぜひ、いい感じに動くようになると嬉しいです。
よろしくおねがいします 🙏

**Comment by the-red** [comment]
@mshrtsr
実装してくださったんですね！
めっちゃ嬉しいです。ありがとうございます 😄

**Comment by mshrtsr** [comment]
@the-red 
こちら対応が遅くなり申し訳ありません。

kintone/js-sdk#1495 でrest-api-clientにhttpsAgentを指定できるように対応しました！
次回リリースに反映予定です！

---

Expected Behaviorに書かれていたプロキシ接続とクライアント証明書を同時に使う方法ですが、以下が確認済みです。
※クライアント証明書はTLS接続時にサーバに送信され、認証されています。

### 1. `proxy`オプションと`clientCertAuth`オプションを指定した場合

同時利用できません。
`proxy`オプションを指定した場合は、absolute-formによるプロキシサーバ経由のリクエスト送信となりますが、この際クライアントとcybozu.comとの間で直接のHTTP通信・TLS接続はないため、セキュアアクセスは利用できません。

```
new KintoneRestAPIClient({
  baseUrl: "example.s.cybozu.com",
  proxy: { host: "proxy.example.com", port: 3128 },
  clientCertAuth: { pfx: "...", password: "..." },
});
```

### 2. HTTPトンネリング対応のHTTPSエージェントでプロキシ接続とクライアント証明書を指定した場合

同時利用できます。

HTTPトンネリングによるプロキシ接続では、プロキシサーバとcybozu.comとはTCPのレイヤで通信しており、TLSハンドシェイクやHTTP(S)通信はクライアントとサーバとの間で行われているため、セキュアアクセスが利用できます。

利用するHTTPSエージェントですが、[hpagent](https://github.com/delvedor/hpagent)がメンテナンスもされており良さそうでした。
https-proxy-agent は引数が適切に処理されない不具合(TooTallNate/node-https-proxy-agent#89 )が原因でセキュアアクセスが利用できませんでした。
node-tunnel はあまりメンテナンスされていないのと、pfxファイルをkeyとcertに変換する必要がありそうです。

```
import { HttpsProxyAgent } from "hpagent";
const agent = new HttpsProxyAgent({
  proxy: `http://proxy.example.com:3128`,
  pfx: "...",
  passphrase: "...",
});
new KintoneRestAPIClient({
  baseUrl: "example.s.cybozu.com",
  httpsAgent: agent,
});
```

**Comment by the-red** [comment]
@mshrtsr 
ライブラリ情報までありがとうございますー。

実は最初にここにIssue立てる前の調査段階で、
hpagentは試していたのですが、
https://github.com/kintone/js-sdk-ja/issues/24#issuecomment-996485078 で書いていただいた「Axiosの挙動」と同じ動きになるようで、
弊社のproxyサーバーでは動きませんでした。

クライアント証明書とプロキシの併用は、今現在は必要に迫られてないので、
ひとまずは「自作のAgent経由でプロキシ接続」だけできればOKです。
僕の需要に一番合うのは`https-proxy-agent`ですかねー。
