### ISSUE TITLE
rest-api-client の getAllRecordsでカーソルの上限エラーになる

### ISSUE THREAD

**Issue by shiroko** [kintone/js-sdk-ja#26]
## Target Package（対象パッケージ）

- @kintone/rest-api-client 2.0.36

## Environment（環境）

- Operating System（OS）: Windows10
- Browser（ブラウザ環境の場合）: Chrome 99.0.4844.51

## Current Behavior（現在の挙動）

getAllRecords() を orderBy あり、 withCursor 無しで複数回コールしていると「KintoneRestAPIError: [429] [GAIA_TM12] 作成できるカーソルの上限に達しているため、カーソルを作成できません。不要なカーソルを削除するか、しばらく経ってから再実行してください。 (jn85lmG7HYFNuvOYqaV0)」のエラーが表示されます。

getAllRecords() は await 付きでコールしており、同期的に複数回コールしています。

## Expected Behavior（期待する挙動）

getAllRecords() を orderBy あり、 withCursor 無しで コールしたとき、全レコードを取得し終えたら、カーソルを削除することによって、前述のエラーを回避できると思いますがいかがでしょうか。

**Comment by shintaroNagata** [comment]
@shiroko 
フィードバックありがとうございます！
https://github.com/kintone/js-sdk/issues/1408 で対応検討します。

**Comment by mshrtsr** [comment]
@shiroko 
対応が遅くなり申し訳ありません。
こちらの現象は現在も発生中でしょうか？
手元では再現できなかったため、詳しい再現手順か再現コードを教えていただけると幸いです。

---
カーソルの仕様として、カーソルから取得可能な全てのレコードを取得した際には自動でカーソルが削除されます。

> 有効なカーソルの数は1ドメイン辺り10です。
> 上限に達した場合、次のいずれかが発生するまで新しいカーソルを開くことはできません。
> - 既存のカーソルの1つからすべてのレコードを取得する
> - 既存のカーソルが自動的に削除される前に、明示的に閉じる
> - 既存のカーソルの有効期限が切れる

https://developer.cybozu.io/hc/ja/articles/360029152012#step4

getAllRecords()の挙動はこちらにあたるため、正常終了時にはカーソルは自動で削除されていそうです。

また、エラーが発生した場合は例外処理でカーソルを削除しています。
https://github.com/kintone/js-sdk/blob/a4a112bb0ecc5b75d9c89a078aebea14e4c5007f/packages/rest-api-client/src/client/RecordClient.ts#L339

環境依存の原因としては他のプログラムもカーソルAPIを利用していたり、パラメータの指定に誤りがある可能性も考えられそうです。

**Comment by mshrtsr** [comment]
@shiroko 
こちら一旦クローズとさせていただきます。
また現象発生しましたら改めてIssueの登録をお願いします。
