### ISSUE TITLE
serverless環境下でmodule.createRequire()が正しく動作しない

### ISSUE THREAD

**Issue by sumihiro** [kintone/js-sdk-ja#27]
## Target Package（対象パッケージ）

- @kintone/rest-api-client 2.0.37

## Environment（環境）

- Operating System（OS）:  macOS 12.2.1(ローカルで動かす場合) 及び AWS Lambda(デプロイして動かす場合)
- Node.js version（Node.js環境の場合）: ローカルにインストールされているのは v16.2.0
- 実行環境: serverless 3.10.0 及び serverless-offline 8.5.0

## Current Behavior（現在の挙動）

1. Serverless のテンプレート `aws-nodejs-typescript` を使用してプロジェクトを作成。
2. @kintone/rest-api-client をインストール。
3. `import { KintoneRestAPIClient } from '@kintone/rest-api-client';` を呼ぶと、エラーになって落ちる。

クラッシュする最小構成のプロジェクトを作成してあります。そのプロジェクトの該当箇所はこちらです。

https://github.com/sumihiro/serverless-kintone-demo/blob/58b6aeeb2f1509e6f59b2583f123afe211f564a1/src/functions/hello/kintone.ts#L1

エラーメッセージは次の通りです。

```
✖ The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
✖ TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
```

落ちているのは https://github.com/kintone/js-sdk/blob/f72a24ef14a880a30d9449ec64772ad15dc03e4d/packages/rest-api-client/index.mjs#L3 の `const require = module.createRequire(import.meta.url); `  です。

実行時の `import.meta` を確認すると、 `{}` となっています。 `import.meta.url` が `undefined` なのでエラーになっているようです。

## Expected Behavior（期待する挙動）

正しくimportされたい。

Serverless環境以外では動作することを確認できているので、実行環境依存の問題のようです。Serverless環境下では `deploy` しても `offline` で動作させても同じエラーとなりました。

Serverless側で何か設定を行って回避できれば良いのですが、現状では回避方法が見つかっていません。

何か対応方法はありますでしょうか？

**Comment by ueokande** [comment]
@sumihiro 
ご報告ありがとうございます。報告していただいた挙動はaws-nodejs-typescriptが利用しているesbuildが、rest-api-clientにあるES Moduleのコードをサポートしていないため発生しております。本現象の回避方法は以下のいずれかが考えられます。

## rest-api-clientをトランスパイルしない

本現象はesbuildがbundleするときに、rest-api-clientをトランスパイルして `import.meta` に空オブジェクトを代入することで発生します。そのためrest-api-clientをbundleの対象から外すことで、本現象は回避できるかと思われます。`serverless.ts` にあるesbuildのビルドオプションで、`exclude`プロパティにbundleしないモジュールを指定することができます。

```
      ....
      exclude: ['aws-sdk', '@kintone/rest-api-client'],
      ...
```

## esbuildを使わない

もう１つの方法が、esbuildを利用しない方法です。aws-nodejs-typescriptは現在[Legacy](https://github.com/serverless/examples/tree/v3/legacy/aws-nodejs-typescript)扱いとなっており、代わりに[aws-node-http-api-typescript](https://github.com/serverless/examples/tree/v3/aws-node-http-api-typescript)というテンプレートが提供されております。こちらのテンプレートでは内部でesbuildではなくTypeScriptを利用しているので、本現象は発生しないかと思われます。

**Comment by sumihiro** [comment]
@ueokande 
ご対応ありがとうございます！

今回は aws-node-http-api-typescript を利用する方法で正しい動作を確認できました。
(ただ、serverless.ymlとpackage.jsonでバージョン指定の齟齬があり修正を必要としましたが）

詳細なご説明ありがとうございました。
