### ISSUE TITLE
@kintone/rest-api-client にて画像サムネイル（サイズ小）の取得

### ISSUE THREAD

**Issue by shirogani** [kintone/js-sdk-ja#28]
## Package（対象パッケージ）

- @kintone/rest-api-client

## Why（なぜ）

@kintone/rest-api-client にて画像サムネイルの取得 API の追加、もしくはなんらかの形でのサムネイルの取得方法の教示をお願いしたいと思っております。

私は、[じぶんページ](https://kintone-sol.cybozu.co.jp/integrate/sonicgarden001.html)や[じぶんフォーム](https://kintone-sol.cybozu.co.jp/integrate/sonicgarden003.html)という、 kintone 連携サービスの開発者です。
じぶんページにてレコード詳細画面を表示するときに、添付ファイルも表示します。
添付ファイルが画像タイプだった場合、 img タグで小さく表示するのですが、そのままのサイズ（3MBの画像は3MBそのまま）でダウンロードしており、画像が多く添付されている場合（例えば顧客の中には60枚添付しているなんてこともありました）、暴力的なダウンロード負荷があり、スマホ回線程度では辛いものがあります。
kintone を見たところ、サムネイル加工がされているようで、せいぜい数十KB程度まで落としているので、多少粗い画像でも、そちらを利用したいと考えております。
顧客はサムネイルの表示を望んでおられますし（画像を画像のファイル名で判断するのは困難、kintone でもサムネイル表示をされている）、このままでは kintone サーバーにも大きく負荷をかけ続けてしまいます。

<img width="543" alt="マイページ" src="https://user-images.githubusercontent.com/15853961/169430710-3211b833-ace2-44c5-8aed-ed0ae29ef375.png">

## What（何を）

@kintone/rest-api-client にて画像サムネイルの取得 API の追加、もしくはなんらかの形でのサムネイルの取得方法の教示をお願いしたいと思っております。

**Comment by mshrtsr** [comment]
@shirogani 
フィードバックありがとうございます！

こちらはkintone REST APIでも対応する機能が提供されていないものですね。
現時点だとrest-api-clientでの提供は予定しておりませんが、
社内にも共有して引き続き検討させていただきます。

**Comment by mshrtsr** [comment]
こちらは社内の検討事項に追加させていただいたためクローズさせていただきます！！
