### ISSUE TITLE
offsetの上限値制限に関する warning 文言

### ISSUE THREAD

**Issue by r3-yamauchi** [kintone/js-sdk-ja#3]
2020年7月の定期メンテナンス以降に契約・お試し開始した kintone環境で offset に 10,000 よりも大きい値を指定して レコード一括取得API を実行すると
```
code: "GAIA_QU02"
message: "offset には 10,000 以下の値を指定してください。"
```
が発生して結果を取得できません。

https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/src/client/RecordClient.ts#L120

の `Warning: The maximum offset value will be limited to 10,000 in the future.` という文言は `Warning: The maximum offset value is limited to 10,000.` の方が適切でないでしょうか。

**Comment by koba04** [comment]
@r3-yamauchi 
Issue ありがとうございます！
そうですね、こちら新しい環境についてはすでに制限が適用されているため、提案頂いた文言の方が正しいです。

下記のリリースにある通り、7 月版のタイミングでは既存の環境に対してはまだ適用されないため、それを踏まえて文言や対応をどうするか検討したいと思います。
https://kintone.cybozu.co.jp/update/main/2020-07.html

ありがとうございます！

**Comment by zaki-yama** [comment]
@r3-yamauchi 
https://github.com/kintone/js-sdk/pull/470
にて、offsetに制限が適用されている環境についてはwarningを表示しない対応を行いました。
2020年7月版のアップデート以前から利用していた環境ではエラーが表示されないため、warningのメッセージもそのままとなっています。
また、上記の対応を取り込んだバージョンを [@kintone/rest-api-client v1.7.1](https://www.npmjs.com/package/@kintone/rest-api-client/v/1.7.1) をリリース済みです。

ご報告ありがとうございました！
