### ISSUE TITLE
getAllRecordsWithCursorで結果0件の場合にカーソルを削除

### ISSUE THREAD

**Issue by m-ando-japan** [kintone/js-sdk-ja#30]
## Package（対象パッケージ）

- @kintone/rest-api-client

## Why（なぜ）

getAllRecordsWithCursorにおいて、現状のコードはcatchされたエラーがある場合のみカーソル削除しているようです。
https://github.com/kintone/js-sdk/blob/d867a027ea251ca109f2e6ceea86105b7e11be57/packages/rest-api-client/src/client/RecordClient.ts#L330

しかし、こちらの記載にあるように結果0件の場合10分後まで作成されたカーソルが削除されないようです。
https://developer.cybozu.io/hc/ja/articles/360029152012#comment_4747049372185

## What（何を）

連続して0件の検索をWithCursorで実行した場合、不要なカーソルが残る結果となるため、明示的に削除する処理を追加必要ではないでしょうか？

**Comment by mshrtsr** [comment]
Related to https://github.com/kintone/js-sdk-ja/issues/26

**Comment by mshrtsr** [comment]
@m-ando-japan 

フィードバックありがとうございます。
こちらの挙動ですが、手元では再現できなかったため、詳しい再現手順か再現コードを教えていただけると幸いです。

---

カーソルの仕様として、カーソルから取得可能な全てのレコードを取得した際には自動でカーソルが削除されます。
こちらの挙動はレコードが0件のカーソルにおいても同様です。

> 有効なカーソルの数は1ドメイン辺り10です。
> 上限に達した場合、次のいずれかが発生するまで新しいカーソルを開くことはできません。
> - 既存のカーソルの1つからすべてのレコードを取得する
> - 既存のカーソルが自動的に削除される前に、明示的に閉じる
> - 既存のカーソルの有効期限が切れる

https://developer.cybozu.io/hc/ja/articles/360029152012#step4

<details>
<summary>再現コード</summary>

```javascript
    // 対象レコードが0件のカーソルを作成
    const resp = await apiClient.record.createCursor({
      app: APP_ID,
      query: "作成日時 = TODAY()", // 該当するレコードが0件のクエリ
    });
    console.log(resp);
    const id = resp.id;

    // カーソルからレコードを取得
    const resp2 = await apiClient.record.getRecordsByCursor({
      id,
    });
    console.log(resp2);

    // カーソルの削除
    const resp3 = await apiClient.record.deleteCursor({
      id,
    });
    console.log(resp3);
```

実行結果（一部抜粋）
レコード取得の実行後にカーソルが自動で削除されているため、カーソルの削除が失敗します。
```
  console.log
    { id: '<カーソルID>, totalCount: '0' }

      at Object.log (src/__tests__/test.test.ts:15:13)

  console.log
    { records: [], next: false }

      at Object.log (src/__tests__/test.test.ts:20:13)


[404] [GAIA_CN01] Specified cursor does not exist or has already expired. ()
KintoneRestAPIError: [404] [GAIA_CN01] Specified cursor does not exist or has already expired. (cfRksjbqvWDn7Kfa95my)
    at KintoneResponseHandler.Object.<anonymous>.KintoneResponseHandler.handleErrorResponse 
```
</details>

getAllRecordsWithCursor()ではカーソル作成後に必ずレコード取得を実行しているため、
該当するレコードが0件のカーソルにおいても、正常終了時にはカーソルは自動で削除されていると考えられます。

以下のようにgetAllRecordsWithCursor()を連続実行するコードも試してみましたが、
カーソル上限のエラーは発生しませんでした。

```javascript
    // 対象レコードが0件のカーソルを作成
    for (let i = 0; i < 100; i++) {
      const resp = await apiClient.record.getAllRecordsWithCursor({
        app: APP_ID,
        query: "作成日時 = TODAY()", // 該当するレコードが0件のクエリ
      });
      console.log(resp);
    }
```

---

環境依存の原因としては他のプログラムが同時にカーソルAPIを利用していたり、意図せず実行が非同期になっていたりする可能性も考えられそうです。

**Comment by m-ando-japan** [comment]
こちらの検証方法が誤っていたようです。

提示のコードでカーソルクローズを確認できました。大変失礼しました。
