### ISSUE TITLE
cli-kintoneに一括削除機能が欲しいです

### ISSUE THREAD

**Issue by kojisato2002** [kintone/js-sdk-ja#31]
## Package（対象パッケージ）

cli-kintone 1.2.0

## Why（なぜ）

バッチ処理で不要データの削除を行いたい

## What（何を）

kintone-cli delete

**Comment by mshrtsr** [comment]
@kojisato2002 
フィードバックありがとうございます！

レコードの一括削除機能ですが、現在開発中です。
リリースまでもうしばらくお待ちください。

**Comment by mshrtsr** [comment]
@kojisato2002 
お待たせいたしました！
最新版のv1.3.1にてレコード一括削除が利用可能です。

- Document: https://github.com/kintone/cli-kintone/tree/v1.3.1#delete
- Release: https://github.com/kintone/cli-kintone/releases/tag/v1.3.1

([v1.3.0](https://github.com/kintone/cli-kintone/releases/tag/v1.3.0)でリリースされましたが最新のパッチバージョンをご案内しております)
