### ISSUE TITLE
cli-kintone リダイレクトの指定位置について(もしかすると仕様確認)

### ISSUE THREAD

**Issue by kojisatocybozu** [kintone/js-sdk-ja#32]
## Target Package（対象パッケージ）

cli-kintone version 1.2.0

- @kintone/xxx 0.0.0

## Environment（環境）

- Operating System（OS）:Microsoft Windows [Version 10.0.19045.2486]
- Browser（ブラウザ環境の場合）:コマンド
- Node.js version（Node.js環境の場合）:

## Current Behavior（現在の挙動）

--condition パラメータ以降にリダイレクトを指定するとエラーになる

cli-kintone record export --base-url https://xxx.cybozu.com --app [xxx] --api-token [api_token] --encoding sjis --condition "入庫日 >= \"2022-10-21\" and 入庫日 <= \"2022-11-20\" **> out.csv**
[2023-01-18T11:39:54.403Z] ERROR: KintoneRestAPIError: [400] [CB_VA01] 入力内容が正しくありません。 (A02uBjaH1wkOTh5A2cjC)

こちらはOK
cli-kintone record export --base-url https://xxx.cybozu.com --app [xxx]--api-token [api_token] --encoding sjis **> test11.csv**  --condition "入庫日 >= \"2022-10-21\" and 入庫日 <= \"2022-11-20\"

## Expected Behavior（期待する挙動）

リダイレクトはパラメータの最後に指定しても動作すること

※パートナー様からの問合せにつき、仕様であればそのように回答致します。

**Comment by mshrtsr** [comment]
@kojisatocybozu 
フィードバックありがとうございます！

こちらの現象ですが、手元では再現できなかっため以下の項目を確認いただけますでしょうか？

- クエリ内のダブルクォートは正しくエスケープされているか
- 「こちらはOK」と記載されているコマンドで出力されるCSV（test11.csv）には期待したレコードが含まれているか
- cli-kintoneを実行しているのは環境（コマンドプロンプト(cmd.exe) or PowerShell or WSL）

**Comment by kojisatocybozu** [comment]
早速のご確認ありがとうございます。

> クエリ内のダブルクォートは正しくエスケープされているか
- ブラウザのコピペだとうまくできてませんが、クエリ自体は双方全く同じものなので、エスケープはされているかと思います

> 「こちらはOK」と記載されているコマンドで出力されるCSV（test11.csv）には期待したレコードが含まれているか
- はい、正しく出力されています

> cli-kintoneを実行しているのは環境（コマンドプロンプト(cmd.exe) or PowerShell or WSL）
cmd.exe 及び、git CMD の両方で同様の現象でした。

**Comment by mshrtsr** [comment]
@kojisatocybozu 
ご確認いただきありがとうございます。

cmd.exe上で正しくエスケープされている状態で試しましたが、やはり手元では再現しないようです。
お手数をおかけしますが、より詳細な再現手順か再現コードをお教えいただけますでしょうか？
※再現コードに非公開情報を含む場合は[テクニカルサポート](https://jp.cybozu.help/k/ja/trouble_shooting/developer/developer_qa.html)経由でお問い合わせください。

---

以下の2つのパターンについて、いずれも正しく期待した出力がrecords.csvに保存されました。
（クォーテーションが間違っている場合はどちらも `[CB_VA01] 入力内容が正しくありません。` のエラーが表示されました）

```bat
: リダイレクトをコマンドの末尾に指定した場合
C:\Users\user>cli-kintone.exe record export --base-url https://[subdomain].cybozu.com --api-token[token] --app [app] --encoding sjis --condition "日付 >= \"2023-01-20\" and 日付 <= \"2023-01-21\"" > records.csv

: リダイレクトをコマンドの途中に指定した場合
C:\Users\user>cli-kintone.exe record export --base-url https://[subdomain].cybozu.com --api-token[token] --app [app] --encoding sjis > records.csv --condition "日付 >= \"2023-01-20\" and 日付 <= \"2023-01-21\""
```

**Comment by kojisatocybozu** [comment]
お忙しい中、何度もありがとうございます。リダイレクト指定をパラメター中で指定した場合の「こちらはOK」のクオテーションの最後に閉じるものが不足していても動作していたため、私が勘違いしていました。正しく閉じれば問題ありませんでした。
私の勘違いでお手を煩わせてしまい、大変申し訳ありませんでした。また、迅速にご対応頂きありがとうございました。

**Comment by mshrtsr** [comment]
@kojisatocybozu 
解決したようで何よりです！
こちらクローズさせていただきます。
