### ISSUE TITLE
webpack5でrest-api-client@3.3をビルドすると`Module not found: Error: Can't resolve 'path'`

### ISSUE THREAD

**Issue by the-red** [kintone/js-sdk-ja#36]
## Target Package（対象パッケージ）

- @kintone/rest-api-client >= 3.3.0

## Environment（環境）

- Operating System（OS）: macOS 13.2
- Browser（ブラウザ環境の場合）: 
- Node.js version（Node.js環境の場合）: 16.16.0

## Current Behavior（現在の挙動）

バグとも言い切れないのですが、ビルド環境への非互換があったので確認させてください。

webpack5でrest-api-client@3.3.0以降をimportしてビルドすると、
以下のようなビルドエラーが出るようになりました。

```
ERROR in ./node_modules/mime-types/index.js 16:14-37
Module not found: Error: Can't resolve 'path' in '/Users/xxx/yyy/node_modules/mime-types'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
```

v3.3.0で入った「support auto-detect MIME type for the browser platform」による影響と思います。
https://github.com/kintone/js-sdk/releases/tag/%40kintone%2Frest-api-client%403.3.0

エラーメッセージには、Polyfill (path-browserify) を使う場合・使わない場合で2パターンの対応が書いてあり、
`webpack.config.js`を編集して2パターンとも試して、どちらでもビルドは成功しました。

ここで確認させてもらいたいのですが、
サイボウズさんとして推奨するのは、上記の2パターンのどちらでしょうか？
Polyfillを入れないパターンの`resolve.fallback: { "path": false }`を採用した場合、
v3.3.0の「auto-detect MIME type」の機能は無効になってしまう気はしているので、
Polyfillはしっかり入れるべきでしょうか？

## Expected Behavior（期待する挙動）

* 3.2.0から3.3.0に上げたときのビルドエラーを安全に解決したい
* webpack5でビルドする際のベストプラクティスを知りたい

よろしくお願いします。

**Comment by mshrtsr** [comment]
@the-red 
フィードバックありがとうございます！
こちら対応検討いたします。

**Comment by mshrtsr** [comment]
@the-red 
こちら、意図せず Node.js のbuilt-in パッケージ（`path`）への依存が含まれてしまっていました。
https://github.com/kintone/js-sdk/issues/1939 で対応進めさせていただきます！

**Comment by mshrtsr** [comment]
@the-red 
お待たせしました。
こちら 本日リリースした @kintone/rest-api-client@3.3.3 にて修正しました。

- release: https://github.com/kintone/js-sdk/releases/tag/%40kintone%2Frest-api-client%403.3.3
- PR: https://github.com/kintone/js-sdk/pull/1943

お手数おかけしますが上記バージョンでpolyfillなしでビルドできるかご確認いただけますと幸いです。

**Comment by the-red** [comment]
@mshrtsr 
早速の対応ありがとうございました！
試してみたところ、問題なくビルド成功しました！！！
