### ISSUE TITLE
コマンドラインツールのログについて

### ISSUE THREAD

**Issue by yszmkn2** [kintone/js-sdk-ja#37]
V0からV1にコマンドラインツールの移行を実施してますが、
batファイルより実行すると画面がすぐに落ちます。
原因がわからないのでログをエクスポートする機能はあるのでしょうか？
以上よろしくお願いいたします。

**Comment by mshrtsr** [comment]
@yszmkn2 
フィードバックありがとうございます！
画面（標準エラー出力）に表示されるログ以外に実行時情報を出力する機能は搭載されていませんね、、、

デバッグを行いやすくしたいという要望は社内でも認識しており、
現在ログ内容の改善を検討しておりますので、そちらをお待ちいただけると幸いです。

**Comment by yszmkn2** [comment]
ご回答ありがとうございます。

原因がわからないのですが、どのように特定したらよろしいですか？
ちなみにcybozu.com共通のログに表示されていないので、それ以前の問題のようです。。

**Comment by mshrtsr** [comment]
@yszmkn2 

こちらコマンドの途中で改行する場合には行末にハット記号`^`をつけていただく必要があります。
ご確認よろしくお願いいたします。

```bat
start /wait cli-kintone.exe record import ^
--base-url https://example.cybozu.com/ ^
--app 123 ^
--username username ^
--password password ^
--file-path records.csv ^
--update-key "Key"
pause
exit /b %ERRORLEVEL%
```

**Comment by yszmkn2** [comment]
ハット記号^が改行コードの意味かと思ってました。。

すいません！解決しました。ありがとうございます。助かりました。

**Comment by mshrtsr** [comment]
@yszmkn2 
解決したようでよかったです！
こちら元の問題が解決されていそうなのでクローズさせていただきます。
（ログの改善については今後も検討進めさせていただきます）
