### ISSUE TITLE
upsertRecordの条件に重複が許可されたフィールドを指定したい

### ISSUE THREAD

**Issue by potaracom** [kintone/js-sdk-ja#4]
## Package（対象パッケージ）

- @kintone/rest-api-client

## Why（なぜ）

例えばルックアップフィールドは重複禁止が設定できませんが、ルックアップフィールドを条件にupsertRecordを実行したいです。
現状ではget -> add/updateという処理を書く必要があり不便です。

## What（何を）

upsertRecordの条件に、重複が許可されたフィールドを指定できる機能を追加したいです。
get結果のレコード番号を条件に更新すれば良いと思っています。

**Comment by zaki-yama** [comment]
@potaracom 
フィードバックありがとうございます！
いただいた内容から、

- ルックアップフィールドを条件にしたときの結果が1件であることを期待しており、1件のレコードを更新したい
- ルックアップフィールドを条件にしたときの結果が複数件の可能性もあり、その際は条件に合致したレコードをまとめて更新したい

などの可能性が考えられたのですが、意図しているのは前者でしょうか？

差し支えなければ、より詳細なユースケースを教えていただけると助かります。

**Comment by potaracom** [comment]
@zaki-yama 
今回のケースは前者に該当します。

建築物マスターアプリと点検結果報告アプリがあります。
各アプリのレコードは1:1で紐づき、紐付けるキーはルックアップフィールドです。

外部サービスからREST APIを利用して点検報告アプリに登録する運用となっています。
点検は年に1回で初回は追加、2回目以降は更新処理が必要になります。

外部サービスと建築物マスターアプリはキーを含む最新の情報が日々反映されます。

**Comment by zaki-yama** [comment]
@potaracom 
ありがとうございます！具体的な利用シーンを記載いただけて、非常に参考になりました。

upsertに限らずrest-api-client全体でupdateKeyの仕様を見直すことになると思いますので、ご要望にお応えできるかどうかすぐに明言はできかねますが、検討させていただきます。

**Comment by mshrtsr** [comment]
こちらは社内の検討事項に追加させていただいたためクローズさせていただきます。
