### ISSUE TITLE
[Bug] Lambda関数内でREST API Clientのコンストラクタを呼ぶと`The argument 'filename' must be a file URL object`のエラーが出る

### ISSUE THREAD

**Issue by the-red** [kintone/js-sdk-ja#41]
### 概要

AWS Lambdaの関数を、CDKを使ってTypeScriptで書いています。
Lambda内でkintone REST API Clientを使ってkintoneにアクセスしたいのですが、
`new KintoneRestAPIClient()`を呼んだ時点でこのようなエラーが発生してしまい、
全く動かすことができませんでした。

```
{
  "errorType": "TypeError",
  "errorMessage": "The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined",
  "trace": [
    "TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined",
    "    at new NodeError (node:internal/errors:405:5)",
    "    at Function.createRequire (node:internal/modules/cjs/loader:1375:11)",
    "    at Object.<anonymous> (/var/task/index.js:40:38)",
    "    at Module._compile (node:internal/modules/cjs/loader:1256:14)",
    "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
    "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
    "    at Module._load (node:internal/modules/cjs/loader:960:12)",
    "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
    "    at require (node:internal/modules/cjs/helpers:119:18)",
    "    at _tryRequireFile (file:///var/runtime/index.mjs:1002:37)"
  ]
}
```

### 対象パッケージ

@kintone/rest-api-client

### 対象バージョン

5.0.3, 5.0.2

### 再現手順

サンプル用のCDKプロジェクトを作りましたので、
これを使ってそのままAWSにデプロイしてみてください。
https://github.com/the-red/cdk-kintone-rest-api-client

デプロイ後、Lambdaのテスト機能などで動かすと再現します。
（eventオブジェクトは空っぽで大丈夫です）
![CleanShot 2023-11-02 at 11 34 16@2x](https://github.com/kintone/js-sdk-ja/assets/4494300/a5b23630-97e3-4512-80e5-9341bbc92123)

### 期待する挙動

`new KintoneRestAPIClient()`でインスタンスが普通に作成される

### 実際の挙動

`new KintoneRestAPIClient()`でエラーが起きる

### 環境

- AWS Lambda
  - Runtime: Node.js v18 or Node.js v16
  - Arch: arm64 or x86_64

Node.jsバージョンとCPUアーキテクチャは数パターン試しましたが、
どれも同じエラーでした。

**Comment by hung-cybo** [comment]
@the-red 

We received your issue.
We will check and get back to you soon.
Thank you for your reproduction repo. It's really helpful for us.

**Comment by tuanphamcybozu** [comment]
@the-red 
Sorry for the late reply. 
We did the investigation and found the cause of the issue.

When deploying, esbuild doesn’t load CJS dependencies in ESM files.
Workaround:
1. Ignore the issue by bundling files (Rollup, webpack, Vite...) before deploying 
2. Make a specified plugin to resolve CJS ( Ref: [zenn.dev](https://zenn.dev/sosukesuzuki/articles/d8220ba2d869f0) )

Please check the workaround above.
I look forward to hearing back from you.
Thank you!

**Comment by the-red** [comment]
@tuanphamcybozu 
Thanks! I will give it a try.

I think this `js-sdk-ja` repository is a place for us to talk to each other in Japanese,
Is there no longer a Japanese person in charge?

**Comment by mshrtsr** [comment]
@the-red 
すみません、自分が本日対応できなかったので英語メンバーに直接返信してもらいました。
（以前js-sdkに英語で問い合わせいただいていたこともあり、返信の早さを優先しての判断でした）
とはいえ、おっしゃる通りjs-sdk-jaは日本語話者向けリポジトリですので、なるべく日本語で対応します！

**Comment by the-red** [comment]
@mshrtsr 
ありがとうございます！
僕なら英語わかるだろうという理由でしたか😁
スピード重視は助かります。
今後ともよろしくお願いします。

**Comment by mshrtsr** [comment]
@the-red 
いえいえ、むしろ初動は遅くなってしまいすみませんでした。
引き続きよろしくお願いします！！

**Comment by the-red** [comment]
@tasshi-me @tuanphamcybozu 
遅くなりましたが、こちら改めて検証してみました。

教えていただいたesbuildプラグインはイマイチうまくいかなかったのですが、
良く考えたら`import`じゃなくて`require`すればエラーが出ないことに気づいて、
こんなシンプルな方法で回避できました！
https://github.com/the-red/cdk-kintone-rest-api-client/pull/2/files

本件、これでcloseとさせていただきます。ありがとうございました。

**Comment by tasshi-me** [comment]
@the-red 
なるほど、型だけtype importして実体はrequireするというのは思いつきませんでした！
共有ありがとうございます！
