### ISSUE TITLE
Feature request: export Types ( field properties & record values )

### ISSUE THREAD

**Issue by shirogani** [kintone/js-sdk-ja#5]
field properties や record values で、フィールドタイプごとにできるだけ詳細に定義された型を使いたいと思うことが多いのですが、どこかで export されていたりするでしょうか？
それとも実装される予定でしょうか？

このあたりでしょうか。

Field properties
https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/src/client/AppClient.ts#L12-L17

Record values
https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/src/client/RecordClient.ts#L7-L9

よろしくお願いします。
日本語で失礼しました。

**Comment by shintaroNagata** [comment]
@shirogani 
ご意見ありがとうございます！

こちらの issue に関しましては、引き続き対応を進めております。
なので shirogani さんのおっしゃる通り、引き続く作業としてそれら個別のフィールドに関する型を export する予定です。
今しばらくお待ちください。

**Comment by shintaroNagata** [comment]
日本語での議論が中心のためこちらのリポジトリに issue を transfer しました。

**Comment by b4h0-c4t** [comment]
@shirogani 
@kintone/rest-api-client v1.6.0にてリリース致しました。
使い方に関しては[こちらのページ](https://github.com/kintone/js-sdk/blob/master/packages/rest-api-client/docs/typescript.md)が参考になると思われるので、ご活用ください。

**Comment by shirogani** [comment]
ありがとうございます！
独自で型定義などしてたので、かなり助かります！
