### ISSUE TITLE
レコード一括取得のapiについて

### ISSUE THREAD

**Issue by haruna-o** [kintone/js-sdk-ja#6]
## Target Package（対象パッケージ）

- 「rest-api-client」に対する報告です。

## Environment（環境）

- Browser

## Current Behavior（現在の挙動）

- バグかどうかの判断がつかず、こちらの報告にきました。
現在「getAllRecords」のapi使用時に、引数として「condition :  作成者 in (LOGINUSER())」を渡したところ、0件のレコード取得となりました。
この間、エラー表示等はなく処理は進んでおり、本来の目的である3件のレコードの取得がされませんでした。

そこで、「getRecords」apiにも同じquery文を記述してみた所、取得されませんでした。
そのため、これはバグなのか、それとも何か記述の仕様が違ったのか判断つけられなくなりました。

現在対策として「作成者 in ("' + kintone.getLoginUser().code + '")」と記述を行いログインユーザーのcodeを渡しており、問題なく動いております。

## Expected Behavior（期待する挙動）

「getAllRecords」apiでも 「作成者 in (LOGINUSER())」が使用できればと思いました。

**Comment by zaki-yama** [comment]
@haruna-o 
ご登録ありがとうございます。
getAllRecords も getRecords も同じように期待通り動いていない状況だと認識しました。
詳しい状況を把握するために3点お伺いしたいのですが、

1) 環境はブラウザとのことですが、rest-api-clientはCybozu CDNからお使いでしょうか？

2) お使いのOSとブラウザを教えていただけますか？

3) 該当のクエリ文字列でREST APIを直接(または、ブラウザ環境であれば `kintone.api()` を使用して)実行したときは期待通りの結果になるでしょうか？
ブラウザ環境であれば、以下のようなコードをカスタマイズ or ブラウザの開発者コンソールで実行するイメージです。

```js
var params = {
  app: 1, // ここは環境によって異なります
  query: '作成者 in (LOGINUSER())'
};

kintone.api('/k/v1/records', 'GET', params)
  .then(function(res) {
    console.log(res); // ここで期待した数のレコードが取得できているか
  });
```

**Comment by haruna-o** [comment]
>環境はブラウザとのことですが、rest-api-clientはCybozu CDNからお使いでしょうか？
-下記URLを使用しております。
　-https://unpkg.com/@kintone/rest-api-client@latest/umd/KintoneRestAPIClient.min.js

>お使いのOSとブラウザを教えていただけますか？
-Windows10
-GoogleChrome
 -バージョン: 84.0.4147.135（Official Build） （64 ビット）


>該当のクエリ文字列でREST APIを直接(または、ブラウザ環境であれば kintone.api() を使用して)実行したときは期待通りの結果になるでしょうか？
-期待通りの結果になりました。

**Comment by zaki-yama** [comment]
@haruna-o 
ありがとうございます。
いただいた情報を元に調査を進めておりますが、事象の再現に至っておりません。

以下のようなカスタマイズで haruna-o さんの環境では期待通りレコードが取得できるでしょうか？
（結果はブラウザの開発者コンソールに出力されます）

```js
const client = new KintoneRestAPIClient();

const params = {
  app: kintone.app.getId(),
  query: "作成者 in (LOGINUSER())",
};

client.record.getRecords(params).then((result) => {
  console.log(result.records);
});
```

あるいは、期待通りに動作しないコードの例をいただくことは難しいでしょうか？

**Comment by haruna-o** [comment]
返事が遅くなってしまい申し訳ありません。

>以下のカスタマイズで haruna-o さんの環境では期待通りレコードが取得できるでしょうか？
-期待通りに取得できました。

>期待通りに動作しないコードの例をいただくことは難しいでしょうか？
実際に使用していたソースは以下となります。
※("xxxxxx"には実際のAPIトークンを入れて調査を行っております。権限は「閲覧・編集」にチェックを入れております。)

await (new KintoneRestAPIClient({
        auth: { apiToken: "xxxxxxxxxxxxxxxx"}
    })).record.getAllRecords({
        "app": kintone.app.getId(),
        "condition": "作成者 in (LOGINUSER())"
    }).then(function(resp) {
          console.log(resp);
          return resp;
    }).catch(function(error) {
        console.log(error);
    });

**Comment by haruna-o** [comment]
実際の調査結果を、画像にてお送りいたします。

１、↓頂いたソースを元に実行した結果画像です。

![2020-08-28_09h17_19](https://user-images.githubusercontent.com/57162395/91508677-24d7e300-e913-11ea-9d57-63a43057de93.png)


２、↓期待通りに動作しないコードの結果画像です。

![2020-08-28_09h22_18](https://user-images.githubusercontent.com/57162395/91508806-74b6aa00-e913-11ea-96c3-cfc510d5407d.png)

**Comment by zaki-yama** [comment]
@haruna-o 
詳細な情報をありがとうございます！
なるほど、API トークンを使って認証されてたのですね。

API トークンを使用した場合、実行ユーザーは Administrator として扱われます。
参考：https://developer.cybozu.io/hc/ja/articles/201941754

> APIトークンを使用した操作は、Administratorによる操作として記録されます。

また、 `LOGINUSER()` 関数は、API を実行したユーザーに変換されます。
参考：https://developer.cybozu.io/hc/ja/articles/202331474#q1-function

こちらからお送りしたサンプルコードはいずれもセッション認証を使用したものでしたが、そちらで期待通りの挙動ということは
API トークンを使用したことによって実行ユーザーが変わり、期待した結果になっていないと考えられます。

**Comment by haruna-o** [comment]
ありがとうございます！分かりました！
