### ISSUE TITLE
環境変数の統一

### ISSUE THREAD

**Issue by koba04** [kintone/js-sdk-ja#7]
## Package（対象パッケージ）

- @kintone/* (全パッケージ)

## Why（なぜ）

現状、パッケージにより環境変数の指定方法や名前が異なるため、複数パッケージを利用する際には環境変数の指定が重複している。

## What（何を）

パッケージで利用する環境変数を統一する。

参考: https://github.com/kintone/js-sdk/tree/master/packages/profile-loader

- [x] それぞれのパッケージで利用している環境変数の洗い出し
- [x] 統一する環境変数名前・値の決定
- [x] 統一する

**Comment by koba04** [comment]
@potaracom 
https://github.com/kintone/js-sdk/pull/458 こちらの Issue についての議論はこちらで進めさせてもらえればと思います。
現状の問題については認識しており、個別のパッケージというよりの全パッケージに対する環境変数を統一する方向で進めていきたいと考えています。

**Comment by potaracom** [comment]
まとめました。

||[profile-loader](https://github.com/kintone/js-sdk/blob/master/packages/profile-loader/src/env.ts#L5)|[plugin-uploader](https://github.com/kintone/js-sdk/blob/master/packages/plugin-uploader/bin/cli.js#L13)|[customize-uploader](https://github.com/kintone/js-sdk/blob/master/packages/customize-uploader/bin/cli.js#L11)|[dts-gen](https://github.com/kintone/js-sdk/blob/master/packages/dts-gen/src/index.ts#L12) *1
| ---- | ---- | ---- | ---- | ---- |
|KINTONE_USERNAME|o|o|o|username|
|KINTONE_PASSWORD|o|o|o|password|
|KINTONE_BASE_URL|o|x|x|host|
|KINTONE_API_TOKEN|o|x|x|-|
|KINTONE_OAUTH_TOKEN|o|x|x|-|
|KINTONE_DOMAIN|x|o|o|-|
|KINTONE_BASIC_AUTH_USERNAME|x|o|o|basicAuthUsername|
|KINTONE_BASIC_AUTH_PASSWORD|x|o|o|basicAuthPassword|
|HTTP_PROXY|x|o|o|proxyHost, proxyPort|
|HTTPS_PROXY|x|o|o|-|

*1 dts-genは環境変数ではなく、オプション名

**Comment by koba04** [comment]
@potaracom 
ありがとうございます、確認します！:tada:
今現在の想定としては、`profile-loader` をベースに、BASIC 認証情報と Proxy 情報に対する環境変数を共通化出来ればと考えています。

**Comment by koba04** [comment]
@potaracom 
大変お待たせしておりますが、環境変数統一の件は https://github.com/kintone/js-sdk/issues/530 の Issue で進めていきます。
dts-gen については、 @potaracom さんが作成してくださった https://github.com/kintone/js-sdk/pull/458 を利用して進めさせて頂きたいと思います 🙏

**Comment by mshrtsr** [comment]
@potaracom 
こちら kintone/js-sdk#530 が完了したのでクローズいたします。
ご協力いただきありがとうございました。
