### ISSUE TITLE
Feature request: api response needs response header

### ISSUE THREAD

**Issue by r3-yamauchi** [kintone/js-sdk-ja#8]
kintone は 検索系の API を実行した際に
> 絞り込み条件にキーワード検索 (like, not like) を含む場合、該当するレコードが10万件に達した時点でkintoneは検索を打ち切ります。
> このとき、レスポンスヘッダに "x-cybozu-warning : Filter aborted because of too many search results." が追加されます。
https://developer.cybozu.io/hc/ja/articles/360029152012

また、同時接続数の上限値、現在値がそれぞれ 「X-ConcurrencyLimit-Limit」、「X-ConcurrencyLimit-Running」という項目として レスポンスヘッダに入れられて返されます。

このように レスポンスヘッダからしか取得できない重要な情報があるため、各APIのレスポンスに HTTPレスポンスヘッダを加えていただきたいです。

また、kintoneへの接続が ネットワークタイムアウトした場合に、それを判別できるようにしていただきたいです。

**Comment by chick-p** [comment]
3つの issue に分けたので、こちらはクローズします。
