### ISSUE TITLE
Feature request: URLプレフィックスなしで baseUrl を指定できないか？

### ISSUE THREAD

**Issue by r3-yamauchi** [kintone/js-sdk-ja#9]
KintoneRestAPIClient のコンストラクタで baseUrl には `https://example.cybozu.com` のように
「https://」を付けてドメインを指定する仕様になっていますが、「https://」を付けるのは冗長の
ように感じます。

例えば
```
const client = new KintoneRestAPIClient({
  domain: "example.cybozu.com",
```
のように「https://」なしで指定すると baseUrl には「https://」を付けて代入されるオプションが
提供されると簡便に使えてありがたいと思います。

**Comment by chick-p** [comment]
https://github.com/kintone/js-sdk-ja/issues/9#issuecomment-596343769 のコメントの通りなので、wontfix としてクローズします。
